changed spaces

diff --git a/.github/workflows/01-building.yaml b/.github/workflows/01-building.yaml
--- a/.github/workflows/01-building.yaml
+++ b/.github/workflows/01-building.yaml
@@ -3,17 +3,17 @@ name: 01-building Blocks
 on: push
 
 jobs: 
-    echo-hello:
-        runs-on: ubuntu-latest
-        steps:
-                -   name: Say Hello
-                run: echo "Hello, world!"
-    echo-goodbye:
-        runs-on: ubuntu-latest
-        steps:
-            -name: Failed step
-            run: |
-                echo "I will fail"   
-                exit 1 
-            -name: Say goodbye
-            run: echo "Goodbye"
+  echo-hello:
+    runs-on: ubuntu-latest
+    steps:
+      -   name: Say Hello
+      run: echo "Hello, world!"
+  echo-goodbye:
+    runs-on: ubuntu-latest
+    steps:
+      -name: Failed step
+      run: |
+        echo "I will fail"   
+          exit 1 
+          -name: Say goodbye
+          run: echo "Goodbye"
